// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // todo: run on chrome with localhost:

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxI8AkX6BYcxypd4noP0tVHYXp9dIZQqQ',
    appId: '1:1044610999991:web:7e88b276052e85ed6f0f32',
    messagingSenderId: '1044610999991',
    projectId: 'eschoolregistration-a2c86',
    authDomain: 'eschoolregistration-a2c86.firebaseapp.com',
    storageBucket: 'eschoolregistration-a2c86.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZGXSb91taSplkeb2bfsEZgvFNmJEAkeU',
    appId: '1:1044610999991:android:7f257d90359331ec6f0f32',
    messagingSenderId: '1044610999991',
    projectId: 'eschoolregistration-a2c86',
    storageBucket: 'eschoolregistration-a2c86.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS8GCn9rTp7IcJib85dUHkYRmlgwva9NA',
    appId: '1:1044610999991:ios:28df031fbee4b1e06f0f32',
    messagingSenderId: '1044610999991',
    projectId: 'eschoolregistration-a2c86',
    storageBucket: 'eschoolregistration-a2c86.firebasestorage.app',
    iosBundleId: 'com.example.eschoolRegistration',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS8GCn9rTp7IcJib85dUHkYRmlgwva9NA',
    appId: '1:1044610999991:ios:28df031fbee4b1e06f0f32',
    messagingSenderId: '1044610999991',
    projectId: 'eschoolregistration-a2c86',
    storageBucket: 'eschoolregistration-a2c86.firebasestorage.app',
    iosBundleId: 'com.example.eschoolRegistration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxI8AkX6BYcxypd4noP0tVHYXp9dIZQqQ',
    appId: '1:1044610999991:web:5262679e4b4ea7ec6f0f32',
    messagingSenderId: '1044610999991',
    projectId: 'eschoolregistration-a2c86',
    authDomain: 'eschoolregistration-a2c86.firebaseapp.com',
    storageBucket: 'eschoolregistration-a2c86.firebasestorage.app',
  );
}
